apiVersion: v1
kind: Service
metadata:
  name: app  
labels:
    app.kubernetes.io/name: app
spec:
  type: LoadBalancer
  ports:
  - name: app
    port: 3003
    nodePort: 32723
  externalIPs:
    - 51.250.85.107
  selector:
    app.kubernetes.io/name: app 

