apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels: 
    app.kubernetes.io/name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: gnmakarov/devops
          args:  
            - sh
            - -c
            - python manage.py migrate && python manage.py runserver 0.0.0.0:3003 
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: POSTGRES_DB
          ports:
            - containerPort: 3003      
          resources: {}
status: {}
